/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as StartRouteImport } from './routes/start'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminCatalogueRouteImport } from './routes/admin.catalogue'
import { Route as AdminCrewRouteImport } from './routes/admin.crew'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminMemoryRouteImport } from './routes/admin.memory'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminJobsIndexRouteImport } from './routes/admin.jobs.index'
import { Route as AdminJobsIdRouteImport } from './routes/admin.jobs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrewRoute = AdminCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/availability': typeof AvailabilityRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/home': typeof HomeRoute
  '/inventory': typeof InventoryRoute
  '/logistics': typeof LogisticsRoute
  '/quote': typeof QuoteRoute
  '/start': typeof StartRoute
  '/upload': typeof UploadRoute
  '/voice': typeof VoiceRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/crew': typeof AdminCrewRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/availability': typeof AvailabilityRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/home': typeof HomeRoute
  '/inventory': typeof InventoryRoute
  '/logistics': typeof LogisticsRoute
  '/quote': typeof QuoteRoute
  '/start': typeof StartRoute
  '/upload': typeof UploadRoute
  '/voice': typeof VoiceRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/crew': typeof AdminCrewRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin': typeof AdminIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analysis': typeof AnalysisRoute
  '/availability': typeof AvailabilityRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/home': typeof HomeRoute
  '/inventory': typeof InventoryRoute
  '/logistics': typeof LogisticsRoute
  '/quote': typeof QuoteRoute
  '/start': typeof StartRoute
  '/upload': typeof UploadRoute
  '/voice': typeof VoiceRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/catalogue': typeof AdminCatalogueRoute
  '/admin/crew': typeof AdminCrewRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analysis'
    | '/availability'
    | '/booking'
    | '/confirmation'
    | '/home'
    | '/inventory'
    | '/logistics'
    | '/quote'
    | '/start'
    | '/upload'
    | '/voice'
    | '/admin/ai'
    | '/admin/calendar'
    | '/admin/catalogue'
    | '/admin/crew'
    | '/admin/customers'
    | '/admin/memory'
    | '/admin/pricing'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/vehicles'
    | '/admin/'
    | '/admin/jobs/$id'
    | '/admin/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/availability'
    | '/booking'
    | '/confirmation'
    | '/home'
    | '/inventory'
    | '/logistics'
    | '/quote'
    | '/start'
    | '/upload'
    | '/voice'
    | '/admin/ai'
    | '/admin/calendar'
    | '/admin/catalogue'
    | '/admin/crew'
    | '/admin/customers'
    | '/admin/memory'
    | '/admin/pricing'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/vehicles'
    | '/admin'
    | '/admin/jobs/$id'
    | '/admin/jobs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analysis'
    | '/availability'
    | '/booking'
    | '/confirmation'
    | '/home'
    | '/inventory'
    | '/logistics'
    | '/quote'
    | '/start'
    | '/upload'
    | '/voice'
    | '/admin/ai'
    | '/admin/calendar'
    | '/admin/catalogue'
    | '/admin/crew'
    | '/admin/customers'
    | '/admin/memory'
    | '/admin/pricing'
    | '/admin/quotes'
    | '/admin/settings'
    | '/admin/vehicles'
    | '/admin/'
    | '/admin/jobs/$id'
    | '/admin/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalysisRoute: typeof AnalysisRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BookingRoute: typeof BookingRoute
  ConfirmationRoute: typeof ConfirmationRoute
  HomeRoute: typeof HomeRoute
  InventoryRoute: typeof InventoryRoute
  LogisticsRoute: typeof LogisticsRoute
  QuoteRoute: typeof QuoteRoute
  StartRoute: typeof StartRoute
  UploadRoute: typeof UploadRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue': {
      id: '/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crew': {
      id: '/admin/crew'
      path: '/crew'
      fullPath: '/admin/crew'
      preLoaderRoute: typeof AdminCrewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCatalogueRoute: typeof AdminCatalogueRoute
  AdminCrewRoute: typeof AdminCrewRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJobsIdRoute: typeof AdminJobsIdRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCatalogueRoute: AdminCatalogueRoute,
  AdminCrewRoute: AdminCrewRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminJobsIdRoute: AdminJobsIdRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalysisRoute: AnalysisRoute,
  AvailabilityRoute: AvailabilityRoute,
  BookingRoute: BookingRoute,
  ConfirmationRoute: ConfirmationRoute,
  HomeRoute: HomeRoute,
  InventoryRoute: InventoryRoute,
  LogisticsRoute: LogisticsRoute,
  QuoteRoute: QuoteRoute,
  StartRoute: StartRoute,
  UploadRoute: UploadRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
